package com.evault.audit;

public enum AuditEventType {
    LOGIN,
    LOGIN_FAILED,
    LOGOUT,
    USER_REGISTERED,
    USER_STATUS_CHANGED,
    CASE_CREATED,
    CASE_UPDATED,
    CASE_ASSIGNED,
    DOCUMENT_UPLOADED,
    DOCUMENT_VIEWED,
    DOCUMENT_DOWNLOADED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,
    DOCUMENT_VERSIONED,
    DOCUMENT_SHARED,
    EVIDENCE_ADDED,
    EVIDENCE_CUSTODY_TRANSFERRED,
    ACCESS_GRANTED,
    ACCESS_REVOKED,
    BLOCKCHAIN_ANCHOR_SUBMITTED,
    BLOCKCHAIN_ANCHOR_CONFIRMED,
    TAMPER_ALERT_TRIGGERED,
    SYSTEM_CONFIG_UPDATED
}
