/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DocumentRegistry {
  export type DocumentRecordStruct = {
    documentHash: BytesLike;
    ipfsCid: string;
    timestamp: BigNumberish;
    registrar: AddressLike;
    caseNumber: string;
    documentType: string;
    isRevoked: boolean;
  };

  export type DocumentRecordStructOutput = [
    documentHash: string,
    ipfsCid: string,
    timestamp: bigint,
    registrar: string,
    caseNumber: string,
    documentType: string,
    isRevoked: boolean
  ] & {
    documentHash: string;
    ipfsCid: string;
    timestamp: bigint;
    registrar: string;
    caseNumber: string;
    documentType: string;
    isRevoked: boolean;
  };
}

export interface DocumentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRegistrar"
      | "authorizedRegistrars"
      | "getDocumentRecord"
      | "lookupByHash"
      | "owner"
      | "registerDocument"
      | "removeRegistrar"
      | "verifyDocument"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DocumentRegistered"
      | "DocumentRevoked"
      | "DocumentVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addRegistrar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedRegistrars",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDocumentRecord",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "lookupByHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDocument",
    values: [string, BytesLike, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRegistrar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocument",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedRegistrars",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDocumentRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lookupByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocument",
    data: BytesLike
  ): Result;
}

export namespace DocumentRegisteredEvent {
  export type InputTuple = [
    documentId: string,
    documentHash: BytesLike,
    ipfsCid: string,
    registrar: AddressLike,
    timestamp: BigNumberish,
    caseNumber: string
  ];
  export type OutputTuple = [
    documentId: string,
    documentHash: string,
    ipfsCid: string,
    registrar: string,
    timestamp: bigint,
    caseNumber: string
  ];
  export interface OutputObject {
    documentId: string;
    documentHash: string;
    ipfsCid: string;
    registrar: string;
    timestamp: bigint;
    caseNumber: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentRevokedEvent {
  export type InputTuple = [
    documentId: string,
    reason: string,
    revoker: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    documentId: string,
    reason: string,
    revoker: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    documentId: string;
    reason: string;
    revoker: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentVerifiedEvent {
  export type InputTuple = [
    documentId: string,
    computedHash: BytesLike,
    isMatch: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    documentId: string,
    computedHash: string,
    isMatch: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    documentId: string;
    computedHash: string;
    isMatch: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DocumentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DocumentRegistry;
  waitForDeployment(): Promise<this>;

  interface: DocumentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRegistrar: TypedContractMethod<
    [_registrar: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedRegistrars: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getDocumentRecord: TypedContractMethod<
    [_documentId: string],
    [DocumentRegistry.DocumentRecordStructOutput],
    "view"
  >;

  lookupByHash: TypedContractMethod<
    [_documentHash: BytesLike],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerDocument: TypedContractMethod<
    [
      _documentId: string,
      _documentHash: BytesLike,
      _ipfsCid: string,
      _caseNumber: string,
      _documentType: string
    ],
    [boolean],
    "nonpayable"
  >;

  removeRegistrar: TypedContractMethod<
    [_registrar: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyDocument: TypedContractMethod<
    [_documentId: string, _computedHash: BytesLike],
    [
      [boolean, string, string, bigint, string, boolean] & {
        isValid: boolean;
        originalHash: string;
        ipfsCid: string;
        registeredTimestamp: bigint;
        registrar: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRegistrar"
  ): TypedContractMethod<[_registrar: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedRegistrars"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getDocumentRecord"
  ): TypedContractMethod<
    [_documentId: string],
    [DocumentRegistry.DocumentRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "lookupByHash"
  ): TypedContractMethod<[_documentHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDocument"
  ): TypedContractMethod<
    [
      _documentId: string,
      _documentHash: BytesLike,
      _ipfsCid: string,
      _caseNumber: string,
      _documentType: string
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeRegistrar"
  ): TypedContractMethod<[_registrar: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyDocument"
  ): TypedContractMethod<
    [_documentId: string, _computedHash: BytesLike],
    [
      [boolean, string, string, bigint, string, boolean] & {
        isValid: boolean;
        originalHash: string;
        ipfsCid: string;
        registeredTimestamp: bigint;
        registrar: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DocumentRegistered"
  ): TypedContractEvent<
    DocumentRegisteredEvent.InputTuple,
    DocumentRegisteredEvent.OutputTuple,
    DocumentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DocumentRevoked"
  ): TypedContractEvent<
    DocumentRevokedEvent.InputTuple,
    DocumentRevokedEvent.OutputTuple,
    DocumentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "DocumentVerified"
  ): TypedContractEvent<
    DocumentVerifiedEvent.InputTuple,
    DocumentVerifiedEvent.OutputTuple,
    DocumentVerifiedEvent.OutputObject
  >;

  filters: {
    "DocumentRegistered(string,bytes32,string,address,uint256,string)": TypedContractEvent<
      DocumentRegisteredEvent.InputTuple,
      DocumentRegisteredEvent.OutputTuple,
      DocumentRegisteredEvent.OutputObject
    >;
    DocumentRegistered: TypedContractEvent<
      DocumentRegisteredEvent.InputTuple,
      DocumentRegisteredEvent.OutputTuple,
      DocumentRegisteredEvent.OutputObject
    >;

    "DocumentRevoked(string,string,address,uint256)": TypedContractEvent<
      DocumentRevokedEvent.InputTuple,
      DocumentRevokedEvent.OutputTuple,
      DocumentRevokedEvent.OutputObject
    >;
    DocumentRevoked: TypedContractEvent<
      DocumentRevokedEvent.InputTuple,
      DocumentRevokedEvent.OutputTuple,
      DocumentRevokedEvent.OutputObject
    >;

    "DocumentVerified(string,bytes32,bool,uint256)": TypedContractEvent<
      DocumentVerifiedEvent.InputTuple,
      DocumentVerifiedEvent.OutputTuple,
      DocumentVerifiedEvent.OutputObject
    >;
    DocumentVerified: TypedContractEvent<
      DocumentVerifiedEvent.InputTuple,
      DocumentVerifiedEvent.OutputTuple,
      DocumentVerifiedEvent.OutputObject
    >;
  };
}
