/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DocumentRegistry } from "./DocumentRegistry";
export * as factories from "./factories";
export { DocumentRegistry__factory } from "./factories/DocumentRegistry__factory";
